### ISSUE TITLE
Got UnknownFiberFormat

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#121]
### Discussed in https://github.com/DASDAE/dascore/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **xunen63** March 30, 2023</sup>
When I try to read a hdf5 file with dascore like this
"
import dascore as dc
file_path = 'E:\\try_PubDAS\FORESEE\FORESEE_UTC_20190404_194804.hdf5'
spool= dc.spool(file_path)
"

I got:

Traceback (most recent call last):
  File "E:\try_PubDAS\DAS_tools.py", line 9, in <module>
    spool= dc.spool(file_path)
  File "D:\softwares\anaconda\envs\pytorch19\lib\functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "D:\softwares\anaconda\envs\pytorch19\lib\site-packages\dascore\core\spool.py", line 327, in spool_from_str
    _format, _version = dc.get_format(path)
  File "D:\softwares\anaconda\envs\pytorch19\lib\site-packages\dascore\io\core.py", line 506, in get_format
    raise UnknownFiberFormat(msg)
dascore.exceptions.UnknownFiberFormat: Could not determine file format of E:\try_PubDAS\FORESEE\FORESEE_UTC_20190404_194804.hdf5</div>

**Comment by d-chambers** [comment]
Thanks @xunen63,

I converted this to an issue to better track its status. 

Dascore doesn't yet support all the formats found in PubDAS, but it is our intention to do so in the future. We have an open tasks on our [project board](https://github.com/orgs/DASDAE/projects/2/views/1) to add support for all the PubDAS formats. I moved the FORESEE testing to high priority so dascore can work for your use case. Unfortunately, the semester has turned out to be rather busy for all of us but we will work on it when we get a chance.

Conversely, the docs have [a section on adding new formats](https://dascore.org/contributing/new_format.html) if you want to give it a go. You can look at the Terra15 io module, which already uses HDF5 as an example.

**Comment by xunen63** [comment]
Thanks for your help！Have a nice day！



---Original---
From: "Derrick ***@***.***&gt;
Date: Thu, Mar 30, 2023 23:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DASDAE/dascore] Got UnknownFiberFormat (Issue #121)




 
Thanks @xunen63,
 
I converted this to an issue to better track its status.
 
Dascore doesn't yet support all the formats found in PubDAS, but it is our intention to do so in the future. We have an open tasks on our project board to add support for all the PubDAS formats. I moved the FORESEE testing to high priority so dascore can work for your use case. Unfortunately, the semester has turned out to be rather busy for all of us but we will work on it when we get a chance.
 
Conversely, the docs have a section on adding new formats if you want to give it a go. You can look at the Terra15 io module, which already uses HDF5 as an example.

**Comment by eileenrmartin** [comment]
Also as a short term fix, there's another open version of the FORESEE data in its original tdms format is available at https://www.datacommons.psu.edu/commonswizard/MetadataDisplay.aspx?Dataset=6290 and the existing DASCore code does support reading this format. We'll still keep this ticket open so we can work to support the format FORESEE is in on PubDAS, but hopefully this helps your research move forwards in the short term!

**Comment by d-chambers** [comment]
Hi @xunen63,

This should now be supported in master. Can you install the current master branch and test it out? Exact instructions are [here](https://github.com/DASDAE/dascore/issues/158#issuecomment-1579350778). Let me know if you run into issues, but I am going to close this for now.
