### ISSUE TITLE
Better unit display

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#209]
## Description
Currently the unit display is a bit overly verbose. For example, "meter" rather than "m" is displayed in plots and such. [This SO post](https://stackoverflow.com/questions/65681490/format-pint-unit-as-short-form-symbol) shows how to configure pint to be more concise.

**Comment by d-chambers** [comment]
This is how the units appear now in the waterfall plot:
![image](https://github.com/DASDAE/dascore/assets/11671536/b0594e33-bd51-4839-bc20-9b1365e28634)

**Comment by ahmadtourei** [comment]
In addition, currently, the axis labels come from the patch dimensions (```patch_0.dims```). However, sometimes patch dimensions do not accurately represent the dimensions. For example, ONYX stores  ```('time', 'channel_number')``` instead of ```('time', 'distance')```. In the example waterfall plot below, the x-axis unit is meters, but the label is incorrectly "Channel_number":
![image](https://github.com/DASDAE/dascore/assets/92008628/88e99298-d53d-468e-a96e-b7e1cfcb9586)

Should we fix the distance axis's title to "Distance (meters)" then?

**Comment by d-chambers** [comment]
>  ONYX stores ('time', 'channel_number') instead of ('time', 'distance')

Huh, that is weird. So the dimension label says "channel_number" but it is actually distance in m? or has the channel number just been trimmed?

**Comment by ahmadtourei** [comment]
Yes, the dimension label says "channel_number" but we see the distance in meters on the plot.

**Comment by d-chambers** [comment]
Ok we should look at the prodml reader, that seems like a big. Do you have a file you can share that does this?

**Comment by ahmadtourei** [comment]
Yes, I'll send a link to your email.

**Comment by ahmadtourei** [comment]
You can also see the problem with reading "gauge_length", which we discussed in #194 using the test data I just shared.
