### ISSUE TITLE
Cannot import dascore on google colab

### ISSUE THREAD

**Issue by SonYida** [DASDAE/dascore#271]
## Description
There becomes a Attribute Error when I tried to import dascore on Google Colab. 

## Example
!pip install dascore
import dascore

## Versions
 - DasCore Version [0.0.13]:
 - Python Version [3.10.12]:
 - Numpy Version [1.23.5]
![bugreport](https://github.com/DASDAE/dascore/assets/146397520/c36ef74b-301d-4e83-8f4c-a7ec4da2c374)

**Comment by d-chambers** [comment]
Hi @SonYida,

It turns out when you install a new numpy version you have to restart the runtime. So run the `!pip install dascore` line then restart the runtime (Runetime -> Restart runtime), then you should be able to import dascore. I just tested this on a new colab environment and it worked for me.

Closing for now, but please re-open this issue if this doesn't fix your issue.

**Comment by SonYida** [comment]
Hi Derrick,

Thanks! This can solve my problem.

Best,
Yida
________________________________
发件人: Derrick Chambers ***@***.***>
发送时间: 2023年10月3日 13:29
收件人: DASDAE/dascore ***@***.***>
抄送: Yida Song (Student) ***@***.***>; Mention ***@***.***>
主题: [EXTERNAL] Re: [DASDAE/dascore] Cannot import dascore on google colab (Issue #271)

CAUTION: This email originated from outside of the Colorado School of Mines organization. Do not click on links or open attachments unless you recognize the sender and know the content is safe.


Hi @SonYida<https://github.com/SonYida>,

It turns out when you install a new numpy version you have to restart the runtime. So run the !pip install dascore line then restart the runtime (Runetime -> Restart runtime), then you should be able to import dascore. I just tested this on a new colab environment and it worked for me.

Closing for now, but please re-open this issue if this doesn't fix your issue.

―
