### ISSUE TITLE
Issue reading a .h5 file

### ISSUE THREAD

**Issue by danilodjor** [DASDAE/dascore#466]
## Description
When attempting to read an HDF5 file using DasCore, I encountered an `AssertionError` related to the `TimeDecimationFilter` attribute in the file's metadata. This prevents the library from processing the file as expected.

The error message is: `AssertionError: not yet implemented` that fires at this line `assert attrs["TimeDecimationFilter"] == 0, "not yet implemented"` in `File ~/pyenv/dascore/lib/python3.12/site-packages/dascore/clients/filespool.py:54, in FileSpool.__init__(self, path, file_format, file_version)`

## Example
Here's an example to reproduce the issue. It is the exact code that I am using to read a h5 file:

```python
import dascore as dc
from dascore.utils.downloader import fetch

# Specify the file path
file_path = fetch('my_folder/my_file.h5')

# Attempt to read the file
spool = dc.spool(file_path)
patch = spool[0]
```

## Expected behavior
The library should successfully read the HDF5 file and populate the spool object.

## Versions
 - OS: macOS Sequoia 15.1.1
 - DasCore Version: 0.1.4
 - Python Version: 3.12.8

**Comment by d-chambers** [comment]
Hi @danilodjor, thanks for opening the issue.

Yes, this was fixed in #465 which has already been merged. Please try reading the file with the master branch. We are doing a few more things but should have a new release soon which will include the fix. 

You can install the master branch directly using pip:

```bash
pip install git+https://github.com/dasdae/dascore.git
```

or using the [dev install instructions](https://dascore.org/contributing/dev_install.html).

By the way, the `fetch` call is primarily for getting dascore data files. You should be able to just do this:

```python
import dascore as dc

# Attempt to read the file
spool = dc.spool(file_path)
patch = spool[0]
```

I will make a note to update the docs to make this more clear.

**Comment by danilodjor** [comment]
Great, thank you for the heads-up @d-chambers, previously I installed it using `pip install dascore`, but now everything works fine!

**Comment by d-chambers** [comment]
Ok sounds good. The fix will be in the next release, at which point the version pip installs will just work, but for the short term I am glad the master branch works. Feel free to create a new issue if something else comes up.
